"""add press release highlights to quarterly_financials

Revision ID: 3049fff86581
Revises: d1f5704c5e60
Create Date: 2026-09-27 22:27:56.310132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3049fff86581'
down_revision: Union[str, Sequence[str], None] = 'd1f5704c5e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quarterly_financials', sa.Column('press_release_highlights', sa.Text(), nullable=True))
    op.add_column('quarterly_financials', sa.Column('press_release_source', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quarterly_financials', 'press_release_source')
    op.drop_column('quarterly_financials', 'press_release_highlights')
    # ### end Alembic commands ###
