"""create_filing_events_table

Revision ID: 440259fd9128
Revises: cf9ad233f7f8
Create Date: 2026-09-27 15:14:59.532801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '440259fd9128'
down_revision: Union[str, Sequence[str], None] = 'cf9ad233f7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filing_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('form', sa.String(length=10), nullable=False),
    sa.Column('accession_number', sa.String(length=30), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cik', 'accession_number', name='uq_filing_event_cik_accession')
    )
    op.create_index(op.f('ix_filing_events_accession_number'), 'filing_events', ['accession_number'], unique=False)
    op.create_index(op.f('ix_filing_events_cik'), 'filing_events', ['cik'], unique=False)
    op.create_index(op.f('ix_filing_events_ticker'), 'filing_events', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filing_events_ticker'), table_name='filing_events')
    op.drop_index(op.f('ix_filing_events_cik'), table_name='filing_events')
    op.drop_index(op.f('ix_filing_events_accession_number'), table_name='filing_events')
    op.drop_table('filing_events')
    # ### end Alembic commands ###
