"""add description last_price market_cap to companies

Revision ID: 44892912880c
Revises: 89c6a34083be
Create Date: 2026-06-07 23:34:10.350346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44892912880c'
down_revision: Union[str, Sequence[str], None] = '89c6a34083be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('description', sa.String(length=2000), nullable=True))
    op.add_column('companies', sa.Column('last_price', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('market_cap', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'market_cap')
    op.drop_column('companies', 'last_price')
    op.drop_column('companies', 'description')
    # ### end Alembic commands ###
