"""add companies and quarterly financials

Revision ID: 89c6a34083be
Revises: 
Create Date: 2026-06-07 00:39:37.669134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c6a34083be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('fiscal_year_end', sa.String(length=4), nullable=True),
    sa.Column('sic', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cik')
    )
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=False)
    op.create_table('quarterly_financials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_period', sa.String(length=4), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('eps_basic', sa.Float(), nullable=True),
    sa.Column('eps_diluted', sa.Float(), nullable=True),
    sa.Column('free_cash_flow', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cik', 'period_end', name='uq_cik_period_end')
    )
    op.create_index(op.f('ix_quarterly_financials_cik'), 'quarterly_financials', ['cik'], unique=False)
    op.create_index(op.f('ix_quarterly_financials_period_end'), 'quarterly_financials', ['period_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quarterly_financials_period_end'), table_name='quarterly_financials')
    op.drop_index(op.f('ix_quarterly_financials_cik'), table_name='quarterly_financials')
    op.drop_table('quarterly_financials')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
